name: example_nav2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: '>=3.22.0'

dependencies:
  cupertino_icons: ^1.0.8
  effective_dart: 1.3.2
  get:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
